version: '2.2'
services:
  mysql:
    build: .
    container_name: app_dump
    environment:
      HOST: 127.0.0.0
      USERNAME: root
      PASSWORD: 12345
      AWS_ACCESS_KEY_ID: 12345
      AWS_SECRET_ACCESS_KEY: 12345
      AWS_DEFAULT_REGION: us-east-1
      AWS_S3_BUCKET: "s3://test" 
    volumes:
      - ./volumes/config:/app/config
      - ./volumes/dump:/app/dump
      - ./volumes/error:/app/error
    network_mode: host
    